from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal, Optional, Union


SourceKind = Literal[
    "arcgis_featureserver",
    "arcgis_mapserver",
    "arcgis_query",
    "text_file",
    "s3_listing",
    "local_file",
    "other",
]

GeometryType = Literal[
    "Point",
    "MultiPoint",
    "LineString",
    "MultiLineString",
    "Polygon",
    "MultiPolygon",
    "Mixed",
    "Raster",
    "Tabular",
    "Unknown",
]


@dataclass(frozen=True)
class SourceBase:
    """
    Base metadata shared by all external data sources.

    These sources are authoritative inputs to the pipeline and are not
    generated by the pipeline itself.
    """
    key: str
    name: str
    kind: SourceKind
    purpose: str

    owner: Optional[str] = None
    expected_geometry: Optional[GeometryType] = None
    expected_crs: Optional[str] = None
    notes: Optional[str] = None
    snapshot_recommended: bool = True
    tags: tuple[str, ...] = field(default_factory=tuple)

    def short_label(self) -> str:
        return f"{self.key} ({self.kind})"


@dataclass(frozen=True)
class RemoteSource(SourceBase):
    """
    External source accessed over HTTP(S), such as ArcGIS layers,
    query endpoints, text manifests, or NOAA/S3 listings.
    """
    url: str = ""

    def identifier(self) -> str:
        return self.url


@dataclass(frozen=True)
class LocalSource(SourceBase):
    """
    External source stored locally in the repository or project data
    directory. This is still a 'source' because the pipeline consumes it
    but does not generate it.
    """
    path: Union[str, Path] = ""

    def path_obj(self) -> Path:
        return Path(self.path)

    def identifier(self) -> str:
        return str(self.path_obj())


def source_dict(*sources: SourceBase) -> dict[str, SourceBase]:
    """
    Build a keyed source dictionary and fail fast on duplicate keys.
    """
    out: dict[str, SourceBase] = {}
    for src in sources:
        if src.key in out:
            raise ValueError(f"Duplicate source key: {src.key}")
        out[src.key] = src
    return out