from __future__ import annotations

from .common import LocalSource, source_dict


# -------------------------------------------------------------------
# Empirical-model external inputs
#
# These are authoritative inputs consumed by the Maine empirical model
# stage but not generated by the pipeline itself.
# -------------------------------------------------------------------


PARCEL_GDB = LocalSource(
    key="parcels_agol_gdb",
    name="Parcels AGOL geodatabase",
    kind="local_file",
    path="data/raw/local/parcelsAGOL.gdb",
    purpose="Parcel polygons used in Maine empirical model feature construction.",
    expected_geometry="Polygon",
    notes="Local parcel geodatabase consumed by the empirical model stage.",
    snapshot_recommended=False,
    tags=("model", "parcels", "local"),
)

SHORELINE = LocalSource(
    key="us_medium_shoreline",
    name="US medium shoreline",
    kind="local_file",
    path="data/raw/local/us_medium_shoreline/us_medium_shoreline.shp",
    purpose="Shoreline geometry used in Maine empirical model feature construction.",
    expected_geometry="LineString",
    notes="Local shoreline shapefile consumed by the empirical model stage.",
    snapshot_recommended=False,
    tags=("model", "shoreline", "local"),
)

MODEL_INPUT_LOCAL_SOURCES = source_dict(
    PARCEL_GDB,
    SHORELINE,
)

MODEL_INPUT_SOURCES = source_dict(
    PARCEL_GDB,
    SHORELINE,
)